config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/boarding"     => "home#boarding",     as: "boarding"
  get "/lessons"      => "home#lessons",      as: "lessons"
  get "/stallions"    => "home#stallions",    as: "stallions"
  get "/forsale"      => "home#forsale",      as: "forsale"
  get "/training"     => "home#training",     as: "training"
  get "/photogallery" => "home#photogallery", as: "photogallery"
  get "/events"       => "home#events",       as: "events"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def boarding

  end

  def lessons

  end

  def stallions

  end

  def forsale

  end

  def training

  end

  def photogallery

  end

  def events

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def is_active?(page_name)
    "active" if params[:action] == page_name
  end
end

app/views/home/boarding.html.erb
<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default green">
    <div class="panel-heading text-center green">
      <h3>Triple C Boarding</h3>
    </div>
    <div class="panel-body text-center green">
      <p>
        Triple C offers both pasture boarding and stall boarding options, we strive to meet any needs you and your horse have while boarding with us, just let us know what you need! We have many different payment plans available from monthly through yearly.
      </p>
      <p>
        Boarding with us is a great way to build your confidence and a great relationship with your horse! We are a very friendly barn and want to work with you to meet your needs. We do group shows, trail rides, team penning and much more!
      </p>

    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>Pricing</h3>
    </div>
    <div class="panel-body text-center yellow">
      <ul>
        <li>
          12x12 Stall with no run: $410/month
        </li>
        <li>
          12x12 Full board with stall and run: $425/month
        </li>
        <li>
          Paddock with shelter (mud free): $440/month*
        </li>
        <li>
          Training and boarding**: $750/month*
        </li>
        <li>
          Horse in Training Lessons: $35/each
        </li>
      </ul>
      <h6>
        <p>
          *You provide the grain.
        </p>
        <p>
          **Your second month of training comes with three free lessons. 60 day commitment to start.
        </p>
        <p>
          ***View our <%= link_to("training page", training_path, class: "training-link") %> for more information on horse training.
        </p>
      </h6>
      <%= image_tag("http://www.triplecpleasurehorses.com/images/boarding.jpg", alt: "boarding stalls") %>
    </div>
  </div>
</div>

app/views/home/events.html.erb
<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default green">
    <div class="panel-heading text-center green">
      <h3>Triple C Events</h3>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>BESC 2015</h3>
    </div>
    <div class="panel-body text-center yellow">
      <p>
        Performance Horse Show
      </p>
      <p>
        <%= link_to "See Flyer", "http://www.triplecpleasurehorses.com/pdf/besc_2015_7.pdf" %>
      </p>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>May 16th</h3>
    </div>
    <div class="panel-body text-center yellow">
      <p>
        Funday Playday
      </p>
      <p>
        <%= link_to "See Flyer", "http://www.triplecpleasurehorses.com/images/events/may-playday-2015.jpg" %>
      </p>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>May 30th</h3>
    </div>
    <div class="panel-body text-center yellow">
      <p>
        Cow Sorting Clinic w/ Casey Park
      </p>
      <p>
        <%= link_to "See Flyer", "http://www.triplecpleasurehorses.com/images/events/cow-sorting.jpg" %>
      </p>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>July 15/16</h3>
    </div>
    <div class="panel-body text-center yellow">
      <p>
        De-Spooking Clinic
      </p>
      <p>
        <%= link_to "See Flyer", "http://www.triplecpleasurehorses.com/images/events/despooking.jpg" %>
      </p>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>2015</h3>
    </div>
    <div class="panel-body text-center yellow">
      <p>
        Triple C Buckle Series
      </p>
      <p>
        <%= link_to "Results Spreadsheet", "http://www.triplecpleasurehorses.com/pdf/sorting-0115.xlsx" %>
      </p>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default green">
    <div class="panel-heading text-center green">
      <h3>Guided Trail Rides</h3>
    </div>
    <div class="panel-body text-center green">
      <p>
        Guided trail rides are 2- 3 hours in length and $150.00 per person. Riders must wear helmets, no children under age of 10. Must be physically able to mount the horse from a mounting block and follow directions. Minimum of two guests, max of four. Weight limit 200lbs. Ride at your own risk. Horse back riding is a potentially hazardous activity.
      </p>
      <p>
        We will follow a beautiful trail up highway 410 outside of Enumclaw where we will embark upon a secluded lake or water fall. This is a good spot to eat lunch (not provided). We will carry your food and drink in our saddle bags. Please dress in layers.
      </p>
      <p>
        If you would like to have a lesson prior to hitting the trail, we suggest that it is a week prior in our indoor arena.
      </p>
    </div>
  </div>
</div>

app/views/home/forsale.html.erb
<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default green">
    <div class="panel-heading text-center green">
      <h3>Triple C Horses For Sale</h3>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>Spirit</h3>
    </div>
    <div class="panel-body text-center yellow">
      <p>
        Spirt one our best lesson and show horses. Been there done that kind of mare. Showmanship, halter, patterns, western pleasure, always top five any show, cattle sorting and gaming, Kidsafe OR small adult looking for a bomb proof mount. She is a beautiful bay mare 15 hands. 225.00 monthly lease opt available. Lessons also available. Private treaty for sale to right home!
      </p>
      <%= image_tag("http://www.triplecpleasurehorses.com/images/spirit-fs.jpg", alt: "boarding stalls", height: "400px", width: "550px") %>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>Eldorado</h3>
    </div>
    <div class="panel-body text-center yellow">
      <p>
        Eldorado 10 year old reg Arabian gelding. 15.1 hands, buckskin in color, very well trained, safe for all levels. Eldorado is seasoned in halter, western riding, trail riding, cattle sorting, gaming, trail obstacles. Eldorado is available for in barn lease or forsale. A very nice all around gelding. Lease price starts at $225.00 monthly. Sale price $ 3500.00      </p>
      <%= image_tag("http://www.triplecpleasurehorses.com/images/eldorado-fs.jpg", alt: "boarding stalls", height: "400px", width: "550px") %>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>Poco</h3>
    </div>
    <div class="panel-body text-center yellow">
      <p>
        She is a very safe and reliable mare. Been camping, trail riding, arena rides with ease. She is easy to cue and has been there done that. Easy keeper, loves to be pampered, nice stall manners good with her feet and is up to date on vaccines. She is available for sale or in barn lease. Please contact Crystal to meet Poco.      </p>
      <%= image_tag("http://www.triplecpleasurehorses.com/images/forsale/poco.jpg", alt: "boarding stalls", height: "400px", width: "550px") %>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default green">
    <div class="panel-heading text-center green">
      <h3>Triple C Leasing</h3>
    </div>
    <div class="panel-body text-center green">
      <p>
        We offer 6 month or 12 month lease options $260.00 a month. Half and full leasing options available. Riding lessons required at one time per week ($35)
      </p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="col-md-9 col-md-offset-2">
  <div id="mainslider" class="flexslider yellow">
    <ul class="slides">
      <% 16.times do |i| %>
        <li>
          <%= image_tag("main/main-#{i + 1}.jpg", alt: "horse") %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default green">
    <div class="panel-heading text-center green">
      <h3>Triple C Pleasure Horses</h3>
    </div>
    <div class="panel-body text-center green">
      <p>
        At Triple C, we want each rider and boarder to feel comfortable with their surroundings as well as with their horse. This is part of the process of making your horse feel comfortable and be understood by its riders.
      </p>
      <p>
        We offer pasture and stall boarding as well as lessons for beginning to intermediate riders. We have an indoor arena to better suit the cold weather and future events of our riders. We also offer trail rides, western pleasure, trail experience and halter breaking.
      </p>
      <p>
        We specialize in matching horses with riders, we can work with you to find the perfect horse for you or the perfect rider for your horse!
      </p>
      <p>
        Feel free to contact us with any questions about any of the services we provide, or to schedule a visit to come check us out!
      </p>
    </div>
  </div>
</div>

app/views/home/lessons.html.erb
<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default green">
    <div class="panel-heading text-center green">
      <h3>Triple C Lessons</h3>
    </div>
    <div class="panel-body text-center green">
      <p>
        Triple C is proud to offer horse riding lessons for all ages and experience levels and can provide a horse for you to learn on if you don't have one! We are very friendly and love to teach people how to properly ride a horse. Some of the basics we teach:
        <ul>
          <li>
            How to be a rider not a passenger
          </li>
          <li>
            How to communicate with your horse
          </li>
          <li>
            How to handle the way your horse is acting
          </li>
          <li>
            How to saddle and maintain your horse
          </li>
        </ul>
      </p>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>Lesson Fee Schedule</h3>
    </div>
    <div class="panel-body text-center yellow">
      <ul>
        <li>
          1.5 Hour Group Lesson: $45
        </li>
        <li>
          1 Hour Private Lesson: $45
        </li>
        <li>
          Additional 30min: $15
        </li>
      </ul>
      <h6>
        <p>
          *Pay attention to your lesson time, time includes grooming, saddling, riding and untacking.
        </p>
      </h6>
    </div>
  </div>
</div>

app/views/home/photogallery.html.erb
<div class="col-md-9 col-md-offset-2">
  <div id="slider" class="flexslider yellow">
    <ul class="slides">
      <% 37.times do |i| %>
        <li data-thumb=<%= "gallery/#{i + 1}.jpg" %>>
          <%= image_tag("gallery/#{i + 1}.jpg", alt: "horse") %>
        </li>
      <% end %>
    </ul>
  </div>

  <div id="carousel" class="flexslider yellow">
    <ul class="slides">
      <% 37.times do |i| %>
        <li data-thumb=<%= "gallery/#{i + 1}.jpg" %>>
          <%= image_tag("gallery/#{i + 1}.jpg", alt: "horse") %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/stallions.html.erb
<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>Triple C Stallions</h3>
    </div>
    <div class="panel-body text-center yellow">
      <p>
        Triple C Pleasure horses is proud to offer the services of Smooth Lil' Jessie a registered 2004 Dun Stallion, FQHR, ABRA, AQHA. Jessie's bloodlines include greats like: Collins Jessie, Poco Bueno, Jessie James, Billy Clegg and King. Contact us for details.
      </p>
      <%= image_tag("http://www.triplecpleasurehorses.com/images/stallion.jpg", alt: "horse rider", width: "550px") %>
    </div>
  </div>
</div>

app/views/home/training.html.erb
<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default green">
    <div class="panel-heading text-center green">
      <h3>Triple C Training</h3>
    </div>
    <div class="panel-body text-center green">
      <p>
        Our training program is well rounded with over 50 years of combined experience! Leandro and Crystal are highly regarded in all disciplines of riding. Together, they look forward to taking you and your horse to the next level in the show ring.  Whether it be up in the hills or to achieve a personal goal! We can teach you and any breed of gaited horse you have in: Western Pleasure, Gaming, Working Cow, and Gaiting. Through our training process your horse gains many hours of trail experience which is a major part of the foundation and confidence building we believe all horses should have. Your horses will enjoy it as much as you!
      </p>
      <p>
        Our goal for you and your horse is increased confidence, developing a better seat and balance in the saddle, and lighter hands and aides for your horse. Trailer loading, clipping and bathing are just part of the daily routine.
      </p>
      <p>
        Training requires a 60 day commitment to get started and starting the second month of training you receive 3 free lessons per month!
      </p>
    </div>
  </div>
</div>

<div class="col-md-9 col-md-offset-2">
  <div class="panel panel-default yellow">
    <div class="panel-heading text-center yellow">
      <h3>Pricing</h3>
    </div>
    <div class="panel-body text-center yellow">
      <ul>
        <li>
          Training (5 days a week with board and hay): $700
        </li>
        <li>
          Lessons: $35/hour
        </li>
        <li>
          Consultation*: $125
        </li>
      </ul>
      <h6>
        <p>
          *Rider Assessment: posture, seating, hand control, balance; Horse Assessment: shoeing, gait, balance, head set; Tack Assessment: saddle fit, bit.
        </p>
      </h6>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripleC</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"/>
    <!-- for FF, Chrome, Opera -->
    <link rel="icon" type="image/ico" href="../assets/favicon.ico" sizes="16x16">
    <link rel="icon" type="image/ico" href="../assets/favicon.ico" sizes="32x32">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
      <%= javascript_include_tag 'application' %>
      <%= javascript_include_tag 'jquery.flexslider' %>
      <%= stylesheet_link_tag    'flexslider'  %>
      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<%= is_active?("index") %>">
              <%= link_to "Home", root_path, {:controller => 'home', :action => 'index'} %>
            </li>
            <li class="<%= is_active?("boarding") %>">
              <%= link_to "Boarding", boarding_path, {:controller => 'home', :action => 'boarding'} %>
            </li>
            <li class="<%= is_active?("lessons") %>">
              <%= link_to "Lessons", lessons_path, {:controller => 'home', :action => 'lessons'} %>
            </li>
            <li class="<%= is_active?("stallions") %>">
              <%= link_to "Stallions", stallions_path, {:controller => 'home', :action => 'stallions'} %>
            </li>
            <li class="<%= is_active?("forsale") %>">
              <%= link_to "For Sale", forsale_path, {:controller => 'home', :action => 'forsale'} %>
            </li>
            <li class="<%= is_active?("training") %>">
              <%= link_to "Training", training_path, {:controller => 'home', :action => 'training'} %>
            </li>
            <li class="<%= is_active?("photogallery") %>">
              <%= link_to "Photo Gallery", photogallery_path, {:controller => 'home', :action => 'photogallery'} %>
            </li>
            <li class="<%= is_active?("events") %>">
              <%= link_to "Events", events_path, {:controller => 'home', :action => 'events'} %>
            </li>
            <li>
              <%= link_to "EFFRA", "http://effra.org" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="row">
      <div class="col-md-7">
        <%= yield %>
      </div>

      <section class="col-md-3">
        <%= image_tag("tripleclogotrans.png", alt: "triple c logo", class: "logo") %>
        <div class="panel panel-default red">
          <div class="panel-heading text-center red">
            <h3>
              Triple C
              <br/>
              Latest News
            </h3>
          </div>
          <div class="panel-body text-center red">
            <p>
              Agreement reached to protect 43,000 acres of White River Forest! Way to go King County and EFFRA
            </p>
            <p class="red-space">
              <%= link_to("Visit Effra's Site", "http://effra.org", class: "panel-link red") %>
            </p>
          </div>
        </div>
      </section>
    </div>

    <footer>
      <ul class="footer">
        <li>
          ©2016 - Triple C Pleasure Horses
        </li>
        <li>
          42829 244th Ave SE - Enumclaw, WA 98022
        </li>
        <li>
          253-569-4804
        </li>
        <li>
          Email: <%= link_to "Info", "mailto:info@triplecpleasurehorses.com" %> | <%= link_to "Webmaster", "mailto:webmaster@triplecpleasurehorses.com" %>
        </li>
        <li>
          <%= link_to "Twitter", "https://twitter.com/CCC_Horses" %> | <%= link_to "Facebook", "www.facebook.com/pages/Triple-C-Pleasure-Horses/161073940597199" %> | <%= link_to "Map", "g.co/maps/3rhfn" %>
        </li>
      </ul>
    </footer>
  </body>
</html>